add resources to gh via update method
osdc/ct-api pull request #18
Opened 2020-07-20 18:39 UTC by daemon1024

2020-07-20 18:41 UTC, daemon1024 commented
![image](https://user-images.githubusercontent.com/47106543/87973749-a18eca80-cae6-11ea-9766-339f81d59813.png)

https://github.com/daemon1024/meetups/pull/9

2020-09-10 04:08 UTC, siddhant-deepsource approved these changes

2020-09-10 04:08 UTC, siddhant-deepsource commented on src/ghop/editmarkdown.js
> +  md = md.data.replace(/uploaded soon/, `[Sildes](${slides})`);
```suggestion
  md = md.data.replace(/uploaded soon/, `[Slides](${slides})`);
```

2020-09-10 04:18 UTC, sidntrivedi012 requested changes

2020-09-10 04:18 UTC, sidntrivedi012 commented on src/ghop/editmarkdown.js
> +  md = md.data.replace(/uploaded soon/, `[Sildes](${slides})`);
```suggestion
  md = md.data.replace(/uploaded soon/, `[Slides](${slides})`);
```

2020-09-10 04:19 UTC, merged